"""empty message

Revision ID: 201fb4631987
Revises: 37d5edf6fa9a
Create Date: 2014-07-20 22:54:39.611720

"""

# revision identifiers, used by Alembic.
revision = '201fb4631987'
down_revision = '37d5edf6fa9a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ## commands auto generated by Alembic - please adjust! ###
    op.create_table('pvdata',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.Text(), nullable=False),
                    sa.Column('ac_1_u', sa.Integer(), nullable=True),
                    sa.Column('ac_1_i', sa.Float(), nullable=True),
                    sa.Column('dc_1_u', sa.Integer(), nullable=True),
                    sa.Column('dc_1_p', sa.Integer(), nullable=True),
                    sa.Column('ac_2_u', sa.Integer(), nullable=True),
                    sa.Column('ac_2_i', sa.Float(), nullable=True),
                    sa.Column('dc_2_u', sa.Integer(), nullable=True),
                    sa.Column('dc_2_p', sa.Integer(), nullable=True),
                    sa.Column('ac_3_u', sa.Integer(), nullable=True),
                    sa.Column('ac_3_i', sa.Float(), nullable=True),
                    sa.Column('dc_3_u', sa.Integer(), nullable=True),
                    sa.Column('dc_3_p', sa.Integer(), nullable=True),
                    sa.Column('current_power', sa.Intege(), nullable=True),
                    sa.Column('daily_energy', sa.Float(), nullable=True),
                    sa.Column('total_energy', sa.Intege(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
    )
    # ## end Alembic commands ###


def downgrade():
    # ## commands auto generated by Alembic - please adjust! ###
    pass
    # ## end Alembic commands ###
