"""Initialize database

Revision ID: 721be6649087
Revises: None
Create Date: 2016-05-18 22:42:25.431499

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "721be6649087"
down_revision = None


def upgrade():
    # commands auto generated by Alembic - please adjust!
    op.create_table(
        "electricity_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("meter_180", sa.Float(), nullable=True),
        sa.Column("meter_280", sa.Float(), nullable=True),
        sa.Column("active_power", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pvdata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("dc_1_u", sa.Integer(), nullable=True),
        sa.Column("dc_1_i", sa.Float(), nullable=True),
        sa.Column("ac_1_u", sa.Integer(), nullable=True),
        sa.Column("ac_1_p", sa.Integer(), nullable=True),
        sa.Column("dc_2_u", sa.Integer(), nullable=True),
        sa.Column("dc_2_i", sa.Float(), nullable=True),
        sa.Column("ac_2_u", sa.Integer(), nullable=True),
        sa.Column("ac_2_p", sa.Integer(), nullable=True),
        sa.Column("dc_3_u", sa.Integer(), nullable=True),
        sa.Column("dc_3_i", sa.Float(), nullable=True),
        sa.Column("ac_3_u", sa.Integer(), nullable=True),
        sa.Column("ac_3_p", sa.Integer(), nullable=True),
        sa.Column("current_power", sa.Integer(), nullable=True),
        sa.Column("daily_energy", sa.Float(), nullable=True),
        sa.Column("total_energy", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "weather_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("temp", sa.Float(), nullable=True),
        sa.Column("pressure", sa.Integer(), nullable=True),
        sa.Column("temp_min", sa.Float(), nullable=True),
        sa.Column("temp_max", sa.Float(), nullable=True),
        sa.Column("humidity", sa.Integer(), nullable=True),
        sa.Column("wind_speed", sa.Float(), nullable=True),
        sa.Column("wind_gust", sa.Float(), nullable=True),
        sa.Column("wind_deg", sa.Integer(), nullable=True),
        sa.Column("clouds", sa.Integer(), nullable=True),
        sa.Column("rain", sa.Integer(), nullable=True),
        sa.Column("snow", sa.Integer(), nullable=True),
        sa.Column("weather_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # end Alembic commands #


def downgrade():
    # commands auto generated by Alembic - please adjust! #
    op.drop_table("weather_data")
    op.drop_table("pvdata")
    op.drop_table("electricity_data")
    # end Alembic commands #
